# Generated by Django 3.2.5 on 2021-07-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210702_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dela',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=100, null=True)),
                ('delo1', models.CharField(blank=True, db_column='Delo1', max_length=100, null=True)),
                ('delo2', models.CharField(blank=True, db_column='Delo2', max_length=100, null=True)),
                ('bullet', models.CharField(blank=True, db_column='Bullet', max_length=5, null=True)),
                ('naboj2', models.CharField(blank=True, db_column='Naboj2', max_length=5, null=True)),
                ('naboj3', models.CharField(blank=True, db_column='Naboj3', max_length=5, null=True)),
                ('penetrace1', models.IntegerField(blank=True, db_column='Penetrace1', null=True)),
                ('penetrace2', models.IntegerField(blank=True, db_column='Penetrace2', null=True)),
                ('penetrace3', models.IntegerField(blank=True, db_column='Penetrace3', null=True)),
                ('poskozeni1', models.IntegerField(blank=True, db_column='Poskozeni1', null=True)),
                ('poskozeni2', models.IntegerField(blank=True, db_column='Poskozeni2', null=True)),
                ('poskozeni3', models.IntegerField(blank=True, db_column='Poskozeni3', null=True)),
                ('nabijeni', models.FloatField(blank=True, db_column='Nabijeni', null=True)),
                ('zamereni', models.FloatField(blank=True, db_column='Zamereni', null=True)),
                ('presnost', models.FloatField(blank=True, db_column='Presnost', null=True)),
            ],
            options={
                'db_table': 'dela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=20, null=True)),
            ],
            options={
                'db_table': 'kategorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Naboje',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=5, null=True)),
            ],
            options={
                'db_table': 'naboje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Narod',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=45, null=True)),
            ],
            options={
                'db_table': 'narod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cislo', models.CharField(blank=True, db_column='Cislo', max_length=5, null=True)),
            ],
            options={
                'db_table': 'tier',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'managed': False},
        ),
    ]
